# Generated by Django 5.2.12 on 2026-08-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_ai_model_id',
            field=models.CharField(blank=True, default='', help_text="Native OpenRouter id for the preferred free rival, e.g. 'google/gemma-4-31b-it:free'", max_length=200),
        ),
    ]
