# Generated by Django 5.2.12 on 2026-08-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_openrouter_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_ai_model_id',
            field=models.CharField(blank=True, default='', help_text="Native model id for the preferred free rival, e.g. 'google/gemma-4-31b-it:free' or 'nvidia/nemotron-3-super-120b-a12b'", max_length=200),
        ),
    ]
