# Generated by Django 5.2.12 on 2026-08-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_provider_neutral_ai_model_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, default=None, help_text="Set when an existing password is changed. Access and refresh tokens whose iat is strictly before this timestamp's Unix second are rejected.", null=True),
        ),
    ]
