# Generated by Django 5.2.17 on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_password_changed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_service_account",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Reserved diagnostic runner identity; participation-restricted; never renamed"
                ),
            ),
        ),
    ]
