# Generated by Django 5.2.12 on 2026-03-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('google', 'Google Gemini'), ('anthropic', 'Anthropic'), ('openrouter', 'OpenRouter'), ('novita', 'Novita AI')], max_length=50)),
                ('model_id', models.CharField(help_text="Gateway model identifier, e.g. 'openai/gpt-5-mini'", max_length=200, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('quality_tier', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('elite', 'Elite')], default='standard', max_length=20)),
                ('cost_per_game', models.DecimalField(decimal_places=2, default=0, help_text='Credits charged per game against this model', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_ai_model',
                'ordering': ['sort_order', 'display_name'],
            },
        ),
    ]
