# Generated by Django 5.2.12 on 2026-08-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_openrouter_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='model_id',
            field=models.CharField(help_text="Native model id for this provider, e.g. 'google/gemma-4-31b-it:free' or 'nvidia/nemotron-3-super-120b-a12b'", max_length=200, unique=True),
        ),
    ]
