# Generated by Django 5.2.12 on 2026-08-24 22:17

from typing import Any

from django.db import migrations
from django.db.migrations.exceptions import IrreversibleError


def irreversible_catalog_money_fields(apps: Any, schema_editor: Any) -> None:
    raise IrreversibleError(
        "Catalog money-field removal cannot be reversed. Restore a verified pre-migration backup."
    )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_provider_neutral_model_help'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='cost_per_game',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='pricing',
        ),
        migrations.RunPython(migrations.RunPython.noop, irreversible_catalog_money_fields),
    ]
