# Generated by Django 5.2.12 on 2026-03-20 07:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for opponent'), ('active', 'Active'), ('finished', 'Finished'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('game_mode', models.CharField(choices=[('vs_ai', 'Human vs AI'), ('vs_human', 'Human vs Human')], default='vs_ai', max_length=20)),
                ('variant_slug', models.CharField(default='english', max_length=50)),
                ('board_state', models.JSONField(default=list, help_text='15x15 grid as list of 15 strings')),
                ('blanks', models.JSONField(default=list, help_text='List of {row, col} for blank tiles')),
                ('premium_used', models.JSONField(default=list, help_text='List of {row, col} for used premiums')),
                ('bag_tiles', models.TextField(default='', help_text='Remaining tiles in order')),
                ('bag_seed', models.IntegerField(default=0)),
                ('current_turn_slot', models.IntegerField(default=0)),
                ('consecutive_passes', models.IntegerField(default=0)),
                ('game_over', models.BooleanField(default=False)),
                ('game_end_reason', models.CharField(blank=True, default='', max_length=50)),
                ('winner_slot', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('ai_model', models.ForeignKey(blank=True, help_text='AI model for vs_ai games', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.aimodel')),
            ],
            options={
                'db_table': 'game_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(help_text='0 or 1')),
                ('rack', models.JSONField(default=list, help_text='Current rack letters as list of strings')),
                ('score', models.IntegerField(default=0)),
                ('pass_streak', models.IntegerField(default=0)),
                ('is_ai', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='game.gamesession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game_player_slot',
                'ordering': ['slot'],
                'unique_together': {('game', 'slot')},
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(help_text='Move sequence number (1-based)')),
                ('kind', models.CharField(choices=[('place', 'Place tiles'), ('exchange', 'Exchange tiles'), ('pass', 'Pass turn')], max_length=20)),
                ('placements', models.JSONField(default=list, help_text='List of {row, col, letter, blank_as} for "place" moves')),
                ('words_formed', models.JSONField(default=list, help_text='List of {word, coords, score} for words created by this move')),
                ('tiles_exchanged', models.IntegerField(default=0, help_text='Number of tiles exchanged')),
                ('points', models.IntegerField(default=0)),
                ('ai_metadata', models.JSONField(blank=True, help_text='Raw AI response metadata for debugging', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.gamesession')),
                ('player_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='game.playerslot')),
            ],
            options={
                'db_table': 'game_move',
                'ordering': ['seq'],
                'unique_together': {('game', 'seq')},
            },
        ),
    ]
