# Generated by Django 5.2.12 on 2026-03-25 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_aiprompt'),
        ('game', '0003_gamesession_total_cost_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='ai_prompt',
            field=models.ForeignKey(blank=True, help_text='AI prompt preset for vs_ai games', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.aiprompt'),
        ),
        migrations.AlterField(
            model_name='move',
            name='kind',
            field=models.CharField(choices=[('place', 'Place tiles'), ('exchange', 'Exchange tiles'), ('pass', 'Pass turn'), ('give_up', 'Give up')], max_length=20),
        ),
    ]
