# Generated by Django 5.2.12 on 2026-08-24 22:17

from typing import Any

from django.db import migrations
from django.db.migrations.exceptions import IrreversibleError


def irreversible_money_state(apps: Any, schema_editor: Any) -> None:
    raise IrreversibleError(
        "Money-state removal cannot be reversed. Restore a verified pre-migration backup."
    )


def scrub_move_billing_metadata(apps: Any, schema_editor: Any) -> None:
    Move = apps.get_model("game", "Move")
    for move in Move.objects.exclude(ai_metadata=None).iterator():
        metadata = move.ai_metadata
        if not isinstance(metadata, dict) or "billing" not in metadata:
            continue
        updated = dict(metadata)
        updated.pop("billing", None)
        move.ai_metadata = updated
        move.save(update_fields=["ai_metadata"])


def drop_billing_tables(apps: Any, schema_editor: Any) -> None:
    schema_editor.execute("DROP TABLE IF EXISTS billing_transaction")
    schema_editor.execute("DROP TABLE IF EXISTS billing_credit_balance")


def delete_billing_permissions_and_content_types(apps: Any, schema_editor: Any) -> None:
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    billing_cts = list(ContentType.objects.filter(app_label="billing"))
    if not billing_cts:
        return
    Permission.objects.filter(content_type__in=billing_cts).delete()
    ContentType.objects.filter(app_label="billing").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gamesession_ai_prompt_alter_move_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='total_cost_usd',
        ),
        migrations.RunPython(scrub_move_billing_metadata, irreversible_money_state),
        migrations.RunPython(drop_billing_tables, irreversible_money_state),
        migrations.RunPython(
            delete_billing_permissions_and_content_types,
            irreversible_money_state,
        ),
    ]
