# Generated by Django 5.2.12 on 2026-08-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_consecutive_scoreless_turns'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumedWsTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'game_consumed_ws_ticket',
            },
        ),
    ]
