# Generated by Django 5.2.17 on 2026-09-06 13:27

from typing import Any

import django.db.models.deletion
import game.models
import uuid
from django.conf import settings
from django.db import migrations, models


def ensure_diagnostic_service_user_forward(apps: Any, schema_editor: Any) -> None:
    from game.services import ensure_diagnostic_service_user

    ensure_diagnostic_service_user()


def unensure_diagnostic_service_user(apps: Any, schema_editor: Any) -> None:
    """Delete the reserved user only if this migration owns it.

    Ownership is ``not user.has_usable_password()`` — the managed
    unusable-password account. A claimant with a usable password is not
    ours and is left in place.

    Historical migration models do not carry ``User.has_usable_password``;
    ``is_password_usable(user.password)`` is the same predicate.

    Accepted residual: reversing drops ``is_diagnostic`` from surviving
    diagnostic sessions (classification loss on rollback). Rows stored
    with ``is_diagnostic=True`` re-forward as their stored value.
    """
    from django.contrib.auth.hashers import is_password_usable

    from game.services import DIAGNOSTIC_SERVICE_USERNAME

    user_model = apps.get_model("accounts", "User")
    user = user_model.objects.filter(username=DIAGNOSTIC_SERVICE_USERNAME).first()
    if user is None:
        return
    if is_password_usable(user.password):
        return
    user.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_service_account_flag"),
        ("catalog", "0003_aiprompt"),
        ("game", "0008_atomic_token_state_schema"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="bag_rng_state",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="is_diagnostic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playerslot",
            name="ai_model",
            field=models.ForeignKey(
                blank=True,
                help_text="Per-seat AI model for diagnostic two-AI sessions",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player_slots",
                to="catalog.aimodel",
            ),
        ),
        migrations.AddField(
            model_name="playerslot",
            name="ai_prompt",
            field=models.ForeignKey(
                blank=True,
                help_text="Per-seat AI prompt for diagnostic two-AI sessions",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="player_slots",
                to="catalog.aiprompt",
            ),
        ),
        migrations.AlterField(
            model_name="gamesession",
            name="board_state",
            field=models.JSONField(
                default=game.models.default_structured_board,
                help_text="15x15 structured cell grid: null or {token, blank_as}",
            ),
        ),
        migrations.AlterField(
            model_name="playerslot",
            name="rack",
            field=models.JSONField(
                default=list,
                help_text="Current rack tokens as list of strings",
            ),
        ),
        migrations.CreateModel(
            name="DiagnosticRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("abandoned", "Abandoned"),
                            ("blocked_dependency", "Blocked by dependency"),
                        ],
                        default="queued",
                        max_length=32,
                    ),
                ),
                (
                    "assist_mode",
                    models.CharField(
                        choices=[
                            ("assisted", "Assisted"),
                            ("authorship", "Authorship"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "instrument",
                    models.CharField(
                        choices=[
                            ("position-set", "Position set"),
                            ("full-game", "Full game"),
                        ],
                        default="full-game",
                        max_length=16,
                    ),
                ),
                ("variant_slug", models.CharField(max_length=50)),
                ("seat0_model_id", models.CharField(max_length=200)),
                ("seat1_model_id", models.CharField(max_length=200)),
                (
                    "position_set_digest",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("max_plies", models.IntegerField(default=0)),
                ("max_provider_requests", models.IntegerField(default=0)),
                ("max_wall_clock_seconds", models.IntegerField(default=0)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("pid", models.IntegerField(blank=True, null=True)),
                (
                    "diagnostic_end_reason",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "executed_runtime_mode",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "score_authority",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("report_path", models.CharField(blank=True, default="", max_length=512)),
                ("log_path", models.CharField(blank=True, default="", max_length=512)),
                ("parameters_json", models.JSONField(default=dict)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnostic_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnostic_runs",
                        to="catalog.aiprompt",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnostic_runs",
                        to="game.gamesession",
                    ),
                ),
            ],
            options={
                "db_table": "game_diagnostic_run",
                "constraints": [
                    models.UniqueConstraint(
                        models.Value(1),
                        condition=models.Q(("status__in", ["queued", "running"])),
                        name="unique_inflight_diagnostic_run",
                    )
                ],
            },
        ),
        migrations.RunPython(
            ensure_diagnostic_service_user_forward,
            unensure_diagnostic_service_user,
        ),
    ]
