# Generated by Django 5.2.17 on 2026-09-07 08:25

import django.db.models.deletion
import uuid
from typing import Any

from django.conf import settings
from django.db import migrations, models




SEED_HOSTS = (
    'openrouter.ai',
    'integrate.api.nvidia.com',
    'api.groq.com',
    'generativelanguage.googleapis.com',
    'api.cloudflare.com',
    'api.mistral.ai',
    'api.aionlabs.ai',
    'router.huggingface.co',
)


def seed_hosts(apps: Any, schema_editor: Any) -> None:
    """Seed the eight shipped hosts. No DNS, no HTTP, no runner spawn."""
    DiagnosticAllowedHost = apps.get_model('game', 'DiagnosticAllowedHost')
    for hostname in SEED_HOSTS:
        DiagnosticAllowedHost.objects.get_or_create(
            hostname=hostname, defaults={'is_active': True, 'created_by': None}
        )


def unseed_hosts(apps: Any, schema_editor: Any) -> None:
    """Remove only seed rows this migration inserted (created_by is null)."""
    DiagnosticAllowedHost = apps.get_model('game', 'DiagnosticAllowedHost')
    DiagnosticAllowedHost.objects.filter(
        hostname__in=SEED_HOSTS, created_by__isnull=True
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_diagnostic_ply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticAllowedHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(help_text='Canonical ASCII hostname; exact-match only (no wildcard or suffix)', max_length=253, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff user who registered the host', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_allowed_hosts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnostic allowed host',
                'verbose_name_plural': 'Diagnostic allowed hosts',
                'db_table': 'game_diagnostic_allowed_host',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('base_url', models.CharField(max_length=300)),
                ('model_id', models.CharField(help_text='Model id metadata, never a URL', max_length=200)),
                ('credential_env_name', models.CharField(choices=[('GROQ_API_KEY', 'GROQ_API_KEY'), ('GEMINI_API_KEY', 'GEMINI_API_KEY'), ('MISTRAL_API_KEY', 'MISTRAL_API_KEY'), ('AION_API_KEY', 'AION_API_KEY'), ('HF_TOKEN', 'HF_TOKEN'), ('CLOUDFLARE_ACCOUNT_ID', 'CLOUDFLARE_ACCOUNT_ID'), ('CLOUDFLARE_API_TOKEN', 'CLOUDFLARE_API_TOKEN'), ('OPENROUTER_API_KEY', 'OPENROUTER_API_KEY'), ('NVIDIA_API_KEY', 'NVIDIA_API_KEY'), ('IBM_CLOUD_API_KEY', 'IBM_CLOUD_API_KEY'), ('IBM_WATSONX_PROJECT_ID', 'IBM_WATSONX_PROJECT_ID'), ('IBM_WATSONX_REGION', 'IBM_WATSONX_REGION')], help_text='Closed credential environment-name set; the value itself is never stored', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='targets', to='game.diagnosticallowedhost')),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff user who registered the target', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnostic_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnostic target',
                'verbose_name_plural': 'Diagnostic targets',
                'db_table': 'game_diagnostic_target',
            },
        ),
        migrations.AddField(
            model_name='playerslot',
            name='diagnostic_target',
            field=models.ForeignKey(blank=True, help_text='Diagnostic-only OpenAI-compatible target; exclusive with ai_model', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_slots', to='game.diagnostictarget'),
        ),
        migrations.AddConstraint(
            model_name='playerslot',
            constraint=models.CheckConstraint(condition=models.Q(('ai_model__isnull', True), ('diagnostic_target__isnull', True), _connector='OR'), name='game_player_slot_model_xor_target'),
        ),
        migrations.RunPython(seed_hosts, unseed_hosts),
    ]
