# Generated by Django 5.2.17 on 2026-09-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game", "0012_diagnostic_targets"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="replay_initial_state",
            field=models.JSONField(
                blank=True,
                editable=False,
                help_text=(
                    "Initial state snapshot {board, premium_used, racks, "
                    "bag_remaining, scores, turn_slot}"
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="move",
            name="replay_before",
            field=models.JSONField(
                blank=True,
                editable=False,
                help_text="State snapshot before move",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="move",
            name="replay_after",
            field=models.JSONField(
                blank=True,
                editable=False,
                help_text="State snapshot after move",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="move",
            name="exchanged_tiles",
            field=models.JSONField(
                blank=True,
                editable=False,
                help_text="Exact list of tile tokens exchanged",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="diagnosticply",
            name="move",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diagnostic_plies",
                to="game.move",
            ),
        ),
        migrations.AddField(
            model_name="diagnosticply",
            name="replay_before",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticply",
            name="replay_after",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="diagnosticply",
            name="ai_trace",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
