# Generated by Django 5.2.17 on 2026-09-08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("game", "0013_admin_replay_capture"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaygroundSimulation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("config_json", models.JSONField(help_text="Immutable match configuration snapshot")),
                ("lease_id", models.UUIDField(blank=True, null=True)),
                ("leased_move_count", models.IntegerField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="playground_simulations", to=settings.AUTH_USER_MODEL)),
                ("game", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="playground_simulation", to="game.gamesession")),
            ],
            options={
                "db_table": "game_playground_simulation",
                "constraints": [models.UniqueConstraint(condition=models.Q(("ended_at__isnull", True)), fields=("created_by",), name="unique_unfinished_playground_simulation")],
            },
        ),
    ]
