import type { AdminReplayPly } from "@/lib/types";
import { moveInspectionTrace } from "@/lib/admin-move-inspection";
import { CompletionSourceBadge } from "./CompletionSourceBadge";

const value = (input: number | undefined) => input === undefined ? "Not recorded" : String(input);

export function ReplayToolTimeline({ move }: { move: AdminReplayPly }) {
  const trace = moveInspectionTrace(move);
  const turnRequests = typeof move.ai_metadata.turn_provider_requests === "number" ? move.ai_metadata.turn_provider_requests : undefined;
  return <div className="space-y-4"><CompletionSourceBadge source={move.ai_metadata.completion_source} />{!trace || trace.attempts.length === 0 ? <p className="text-sm text-stone-400">Tool-call history was not recorded.</p> : trace.attempts.map((attempt) => <section key={attempt.attempt_index} className="rounded-xl border border-amber-300/15 bg-black/25 p-3"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-stone-800 px-2.5 py-1 text-xs font-bold">Attempt {attempt.attempt_index + 1}</span><span className="rounded-full bg-stone-800 px-2.5 py-1 text-xs">{attempt.provider ?? "Provider not recorded"} · {attempt.model_id ?? "Model not recorded"}</span><span className="rounded-full bg-stone-800 px-2.5 py-1 text-xs">Time to submission: {value(attempt.latency_ms)} ms</span><span className="rounded-full bg-stone-800 px-2.5 py-1 text-xs">Attempt requests: {value(attempt.provider_requests_used)}</span><span className="rounded-full bg-stone-800 px-2.5 py-1 text-xs">Turn requests: {value(turnRequests)}</span></div><ol className="mt-3 space-y-2">{attempt.events.map((event) => <li key={event.ordinal} className="rounded-lg border border-stone-700/60 bg-stone-950/70 p-3 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-stone-100">{event.tool === "phase" ? "Repair phase started" : event.tool}</strong>{event.tool === "validateMove" && typeof event.valid === "boolean" ? <span className={`rounded-full px-2 py-1 text-xs font-black ${event.valid ? "bg-emerald-950 text-emerald-200" : "bg-rose-950 text-rose-200"}`}>{event.valid ? "Valid" : "Rejected"}</span> : null}</div>{event.placements?.length ? <p className="mt-2 text-stone-300">Proposed: {event.placements.map((placement) => `${placement.blank_as ?? placement.letter}@${placement.row + 1},${placement.col + 1}`).join(" · ")}</p> : null}{event.words?.length ? <p className="mt-1 text-stone-300">Words: {event.words.join(", ")}</p> : null}{event.rejection_code ? <p className="mt-1 text-rose-300">Reason: {event.rejection_code}</p> : null}{event.tool === "finishMove" ? <p className="mt-1 text-stone-300">Confirmed ready: {event.ready ? "Yes" : "No"}</p> : null}{event.incomplete ? <p className="mt-1 text-amber-300">Call did not complete before terminal capture.</p> : null}</li>)}</ol>{attempt.truncated ? <p className="mt-2 text-xs text-amber-300">Trace truncated; {attempt.omitted_event_count ?? 0} events omitted.</p> : null}</section>)}</div>;
}
